### ISSUE TITLE
[JointTrajectoryController] Revive angle_wraparound option

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_controllers#172] opened 2021-04-21 08:45 UTC
In the current implementation, there is no possibility to wraparound joint angles. Add this functionality from ROS1 version of the controller. Start at [this line](https://github.com/ros-controls/ros_controllers/blob/a075bc36ebf5b81a7dafe911907cc1b781dd0185/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h#L269).

**Comment by shonigmann** [comment] 2021-06-28 23:43
also in #85 ?

**Comment by christophfroehlich** [comment] 2023-10-10 16:18
Duplicate of #85? Anyways, fixed with #772.

**Closed by christophfroehlich** 2023-10-10 16:18 UTC
